namespace HandelApp.Shared.Protocol;

/// <summary>
/// Represents a command sent from the web application to the agent over TCP.
/// Serialised as length-prefixed JSON by <see cref="ProtocolSerializer"/>.
/// </summary>
/// <remarks>
/// Not all properties are relevant for every <see cref="CommandType"/>:
/// <list type="bullet">
///   <item><description><see cref="AppId"/> — required for all instance/app commands.</description></item>
///   <item><description><see cref="InstanceName"/> — required for Start, Stop, Status.</description></item>
///   <item><description><see cref="InstanceNumber"/> — required for CreateInstance, DeleteInstance.</description></item>
///   <item><description><see cref="AppDefinition"/> — required for RegisterApp only.</description></item>
/// </list>
/// </remarks>
public sealed record AgentCommand
{
    /// <summary>The operation to perform. Drives dispatch in <see cref="TcpCommandListener"/>.</summary>
    public CommandType    Command        { get; init; }

    /// <summary>
    /// Identity of the user or system that initiated the command.
    /// Populated from <c>User.Identity.Name</c> in the web controllers; used for audit logging only.
    /// </summary>
    public string         RequestedBy    { get; init; } = string.Empty;

    /// <summary>
    /// Unique identifier generated by the sender. The agent echoes it in the matching
    /// <see cref="AgentResponse"/> so the client can correlate responses to requests on a
    /// multiplexed connection.
    /// </summary>
    public Guid           CorrelationId  { get; init; } = Guid.NewGuid();

    /// <summary>
    /// Numeric instance suffix used by <see cref="CommandType.CreateInstance"/> and
    /// <see cref="CommandType.DeleteInstance"/>. <see langword="null"/> for other commands;
    /// defaults to <c>1</c> in the dispatcher when absent.
    /// </summary>
    public int?           InstanceNumber { get; init; }

    /// <summary>
    /// Exact instance name used by Start, Stop, and Status commands
    /// (e.g. "Default" or "Instance-3").
    /// </summary>
    public string         InstanceName   { get; init; } = string.Empty;

    /// <summary>
    /// Case-insensitive application identifier. Required for all commands except
    /// <see cref="CommandType.ListApps"/>.
    /// </summary>
    public string         AppId          { get; init; } = string.Empty;

    /// <summary>
    /// Full app definition payload. Required only for <see cref="CommandType.RegisterApp"/>;
    /// <see langword="null"/> for all other commands.
    /// </summary>
    public AppDefinition? AppDefinition  { get; init; }
}
